#!/bin/bash

#SBATCH --partition=GPU
#SBATCH --job-name=DebU381B_10K
#SBATCH --ntasks-per-node=10
#SBATCH --output=outputdebU381B.out
#SBATCH -o outfiledebU381B.log 
#SBATCH -e errfiledebU381B.txt

#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=natalia.huitzil@cimat.mx
#

# exportar el path hacia los ejecutables de Python
export PATH=$PATH:/opt/anaconda3_titan/bin
source /home/est_posgrado_natalia.huitzil/.bashrc
conda activate compu21

hostname
date
# Ejecutar script

cd /home/clirlab/natalia/Prueba38C/
#cd /home/est_posgrado_natalia.huitzil/ST2/Prueba36/
#cd /home/est_posgrado_natalia.huitzil/.conda/envs/myenv/bin/python3.8
#cd/home/est_posgrado_natalia.huitzil/.conda/envs/myenv/bin/python3.8 runner.py
#/home/est_posgrado_natalia.huitzil/.conda/envs/compu21/bin/python3.8 Cluster_Prueba7_Denoising3curvGaussian.py


python Cluster_Prueba38_DIPOPP_1B_10K.py


date
