#!/bin/bash

#SBATCH --partition=GPU
#SBATCH --job-name=DebU360C_5to25
#SBATCH --ntasks-per-node=10
#SBATCH --output=outputdebU360C_5to25.out
#SBATCH -o outfiledebU360C_5to25.log 
#SBATCH -e errfiledebU360C_5to25.txt

#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=natalia.huitzil@cimat.mx
#

# exportar el path hacia los ejecutables de Python
export PATH=$PATH:/opt/anaconda3_titan/bin
source /home/est_posgrado_natalia.huitzil/.bashrc
conda activate compu21

hostname
date
# Ejecutar script

cd /home/clirlab/natalia/Prueba36C/
#cd /home/est_posgrado_natalia.huitzil/.conda/envs/myenv/bin/python3.8
#cd/home/est_posgrado_natalia.huitzil/.conda/envs/myenv/bin/python3.8 runner.py
#/home/est_posgrado_natalia.huitzil/.conda/envs/compu21/bin/python3.8 Cluster_Prueba7_Denoising3curvGaussian.py

#python Cluster_Prueba36_DIPOPP_1B.py
python Cluster_Prueba36_VectorialTotalVariation_0C.py

date
