#!/bin/bash

#SBATCH --partition=GPU
#SBATCH --job-name=463CdeUo
#SBATCH --ntasks-per-node=10
#SBATCH --output=output463CdebUo.out
#SBATCH -o outfile463CdebUo.log 
#SBATCH -e errfile463CdebUo.txt

#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=natalia.huitzil@cimat.mx
#

# exportar el path hacia los ejecutables de Python
export PATH=$PATH:/opt/anaconda3_titan/bin
source /home/est_posgrado_natalia.huitzil/.bashrc
conda activate compu21

hostname
date
# Ejecutar script

cd /home/clirlab/natalia/Prueba46C/
#cd /home/est_posgrado_natalia.huitzil/ST2/Prueba36/
#cd /home/est_posgrado_natalia.huitzil/.conda/envs/myenv/bin/python3.8
#cd/home/est_posgrado_natalia.huitzil/.conda/envs/myenv/bin/python3.8 runner.py
#/home/est_posgrado_natalia.huitzil/.conda/envs/compu21/bin/python3.8 Cluster_Prueba7_Denoising3curvGaussian.py


#python Cluster_Prueba46_RiemannianGradientNewOPP_0C_debU_25K.py
#python Cluster_Prueba46_GradientRiemannianNewOPP_1C_debG_30K_unicSinpesoOpp.py
#python Cluster_Prueba46_GradientRiemannianNew_2C_debG_23K.py
python Cluster_Prueba46_RiemannianGradientNewOPP_3C_debU_25K.py

date
