#!/bin/bash

#SBATCH --partition=GPU
#SBATCH --job-name=401Cden25rep
#SBATCH --ntasks-per-node=10
#SBATCH --output=output401Cden25rep.out
#SBATCH -o outfile401Cden25rep.log 
#SBATCH -e errfile401Cden25rep.txt

#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=natalia.huitzil@cimat.mx
#

# exportar el path hacia los ejecutables de Python
export PATH=$PATH:/opt/anaconda3_titan/bin
source /home/est_posgrado_natalia.huitzil/.bashrc
conda activate compu21

hostname
date
# Ejecutar script

cd /home/clirlab/natalia/Prueba40C/
#cd /home/est_posgrado_natalia.huitzil/ST2/Prueba36/
#cd /home/est_posgrado_natalia.huitzil/.conda/envs/myenv/bin/python3.8
#cd/home/est_posgrado_natalia.huitzil/.conda/envs/myenv/bin/python3.8 runner.py
#/home/est_posgrado_natalia.huitzil/.conda/envs/compu21/bin/python3.8 Cluster_Prueba7_Denoising3curvGaussian.py


#python Cluster_Prueba40_RiemannianGradient_0C_den25_8K.py
python Cluster_Prueba40_RiemannianGradientRGBOPP_1C_den25_8K.py

date
