#!/bin/bash

#SBATCH --partition=GPU
#SBATCH --job-name=470CdebU
#SBATCH --ntasks-per-node=10
#SBATCH --output=output470CdebU.out
#SBATCH -o outfile470CdebU.log 
#SBATCH -e errfile470CdebU.txt

#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=natalia.huitzil@cimat.mx
#

# exportar el path hacia los ejecutables de Python
export PATH=$PATH:/opt/anaconda3_titan/bin
source /home/est_posgrado_natalia.huitzil/.bashrc
conda activate compu21

hostname
date
# Ejecutar script

cd /home/clirlab/natalia/Prueba47C/
#cd /home/est_posgrado_natalia.huitzil/ST2/Prueba36/
#cd /home/est_posgrado_natalia.huitzil/.conda/envs/myenv/bin/python3.8
#cd/home/est_posgrado_natalia.huitzil/.conda/envs/myenv/bin/python3.8 runner.py
#/home/est_posgrado_natalia.huitzil/.conda/envs/compu21/bin/python3.8 Cluster_Prueba7_Denoising3curvGaussian.py


python Cluster_Prueba47_DIPOPP_0C_den15_6K.py
#python Cluster_Prueba47_UnknownOperatorV4OPP_1C_debU_30K_snOpp.py


date
